replicaCount: 1

kind: Deployment

image:
  pullPolicy: Always
  registry: instrumentisto
  name: coturn
  tag: "4.5.1.3"


# args:
#   - "--arg1"
#   - "--arg2"
#   - "/myArg/"
args:
  - "--stun-only"


# env:
#   myvar: "myvalue"
env: {}


# extraLabels:
#   mylabel: myvalue
extraLabels: {}


# resources: {
#   "requests":
#   {"memory":"200Mi", "cpu":"100m"},
#   "limits":
#   {"memory":"1000Mi", "cpu":"250m"}
#   }
resources: {}


# imagePullSecret: mysecret
imagePullSecret: {}


# mountedSecrets:
#   mySecret:
#     secretName: my-secret
#     items:
#     - key: MySecret
#       path: MySecret
#     mountPath: "/var/run/my-secret"
mountedSecrets: {}


# ingress:
#   enabled: true
#   path: "/somepath"
#   portName: my-port
#   rewrite: "/somepath/$1"
#   annotations:
#     "abc.com/annotation": "true"
#   domain: myaddress.com
#   tls:
#     hosts:
#     - myaddress.com
#     secretName: my-tls-secret
ingress: {}


# service:
#   enabled: true
#   type: ClusterIP
#   ports:
#     http: 
#       port: 1337
#       protocol: TCP
service:
  enabled: true
  type: ClusterIP
  ports:
    stun-tcp: 
      port: 3478
      protocol: TCP
    stun-udp: 
      port: 3478
      protocol: UDP


# tcpProbe:
#   port: 80
#   period: 15
#   delay: 15
tcpProbe:
  port: 3478
  period: 15
  delay: 15


# httpProbe:
#   readyPath: /
#   livePath: /
#   port: 80
#   delay: 15
#   period: 15
httpProbe: {}
  

# execProbe:
#   command:
#     - /bin/bash
#     - -c
#     - sleep
#   delay: 15
#   period: 15
execProbe: {}


# tier: backend
tier: backend


# containerSecurityContext:
#   readOnlyRootFilesystem: true
#   allowPrivilegeEscalation: false
containerSecurityContext: {}


# podSecurityContext:
#   fsGroup: 999
#   runAsUser: 999
#   runAsGroup: 999
podSecurityContext: {}

# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/e2e-az-name
#           operator: In
#           values:
#           - e2e-az1
#           - e2e-az2
#   podAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#     - labelSelector:
#         matchExpressions:
#         - key: security
#           operator: In
#           values:
#           - S1
#       topologyKey: failure-domain.beta.kubernetes.io/zone
affinity: {}          

# persistence:
#   enabled: true
#   storageClassName: local-path
#   storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   annotations: 
#     "helm.sh/resource-policy": "keep"

persistence: {}




# extraVolumeMounts:
#   - mountPath: /tmp
#     name: tmp
extraVolumeMounts: {}


# extraVolumes:
#   - name: tmp
#     emptyDir: {}    
extraVolumes: {}

