{{- define "common-lib.deployment" -}}
apiVersion: apps/v1
kind: {{ .Values.kind }}
{{ tpl ( include "common-lib.deployment-metadata" . ) . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  {{- tpl ( include "common-lib.deployment-spec-template" . ) . }}
    spec:
      restartPolicy: Always
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- range $key, $val := .Values.podSecurityContext }}
        {{ $key }}: {{ $val }}
        {{- end }}
      {{- end }}      
      containers:
      - name: {{ .Release.Name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }} 
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.managedTag }}"
        {{- if .Values.args }}
        args:
          {{- range .Values.args }}
          - {{ . | quote }}
          {{- end }}
        {{- end }}   
        {{- tpl ( include "common-lib.deployment-httpProbe" . ) . }}
        {{- tpl ( include "common-lib.deployment-tcpProbe" . ) . }}
        {{- tpl ( include "common-lib.deployment-execProbe" . ) . }}
        {{- tpl ( include "common-lib.deployment-env" . ) . }}
        {{- tpl ( include "common-lib.deployment-resources" . ) . }}
        {{- tpl ( include "common-lib.deployment-ports" . ) . }}
        volumeMounts:
          {{- tpl ( include "common-lib.deployment-mountedSecrets-volumeMount" . ) . }}
        {{- if .Values.containerSecurityContext }}
        securityContext:
            {{- range $key, $val := .Values.containerSecurityContext }}
            {{ $key }}: {{ $val }}
            {{- end }}
        {{- end }}  
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}       
      volumes: 
      {{- tpl ( include "common-lib.deployment-mountedSecrets-volume" . ) . }}

{{- template "common-lib.service" . -}}
{{- template "common-lib.ingress" . -}}
{{- template "common-lib.localStorage-pvc" . -}}

{{- end }}
