name: svc-cd

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/svc-cd.yaml'
      - 'go.mod'
      - 'go.sum'
      - 'cmd/svc/**'
      - 'pkg/**'
      - 'internal/**'
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
          stable: false
          cache: true
      - name: install ko
        run: go install github.com/google/ko@latest
      - name: Build and push
        env:
          KO_DOCKER_REPO: ghcr.io/memelabs/strims
        run: ko build --tags=${{ contains(github.ref_name, 'dev') && 'dev' || 'latest' }} --platform=linux/amd64,linux/arm64 --base-import-paths ./cmd/svc/
